version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "WS-POC-3"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bgqehuifygis"
s3_prefix = "WS-POC-3"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
